services:
  - type: web
    name: ecom-analytics-backend
    env: python
    plan: free
    buildCommand: pip install --no-cache-dir --no-build-isolation -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: PORT
        value: 10000
